data:
  products: "src/data/OrderDetails.csv"
  sales: "src/data/ListofOrders.csv"
  targets: "src/data/Salestarget.csv"

analysis:
  market_basket:
    min_support: 0.01
    min_confidence: 0.5
  sales_performance:
    target_column: "target"
    actual_column: "sales"